/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyInterface */

#ifndef _Included_MyInterface
#define _Included_MyInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyInterface
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyInterface_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
